Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1842859-sedona-32 pull request #9
Opened 2021-11-05 18:15 UTC by SitnikovaIrina

2021-11-06 07:39 UTC, Dima-Dim requested changes

2021-11-06 07:39 UTC, Dima-Dim commented on catalog.html
> +                      <span class="control-mark"></span>
https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-06

2021-11-06 07:39 UTC, Dima-Dim commented on catalog.html
> +                  <span class="filter-button-apply">Применить</span>
Тут точно без span-а не обойтись?

2021-11-06 07:39 UTC, Dima-Dim commented on catalog.html
> +                <span class="hotel-details-title">Подробнее</span>
И во всех подобных случаях проверить нужен ли span.

2021-11-06 07:39 UTC, Dima-Dim commented on catalog.html
> +                <span class="visually-hidden">Гостиница 4 звезды</span>
Здесь понятно зачем span, а вот в случаях выше, нет.

2021-11-06 07:39 UTC, Dima-Dim commented on styles/styles.css
> +  right: 531px;
На лайве вам должны были показывать как делать центрирование абсолютно спозиционированных элементов. Здесь это не принципиально, но если хеадер будет адаптивным, но такой подход работать не будет.

2021-11-06 07:39 UTC, Dima-Dim commented on styles/styles.css
> +  outline: none;
Если на макете нет чётку указания как будет вести себя элемент при наведении и фокусе лучше оставить поведение по умолчанию.

2021-11-06 07:39 UTC, Dima-Dim commented on styles/styles.css
> +  background-image: url(../imges/svg/dropdown.svg);
`url(../imges/svg/dropdown.svg)` -> `url("../imges/svg/dropdown.svg")`

2021-11-06 17:11 UTC, SitnikovaIrina commented on catalog.html
> +                      <span class="control-mark"></span>
Нас на лайве так учили, что нужен пустой спан с классом. С помощью него стилизовать чекбоксы и радиокнопки. И к нему можно применить псевдоэлементы. С их помощью я нарисовала галочку у чекбоксов и кружок у радио.

2021-11-06 17:12 UTC, SitnikovaIrina commented on catalog.html
> +                  <span class="filter-button-apply">Применить</span>
Тут нужен спан с классом, чтобы задать кнопкам состояния. По стайлгайду у всех кнопок меняется цвет самого текста при нажатии. Я придумала только такой способ как это реализовать.

2021-11-06 17:13 UTC, SitnikovaIrina commented on styles/styles.css
> +  background-image: url(../imges/svg/dropdown.svg);
Исправила

2021-11-06 17:13 UTC, SitnikovaIrina commented on styles/styles.css
> +  right: 531px;
Попробовала сделать по другому. Вроде получилось

2021-11-06 17:16 UTC, SitnikovaIrina commented on styles/styles.css
> +  outline: none;
Убрала

2021-11-07 15:01 UTC, Dima-Dim commented on catalog.html
> +                      <span class="control-mark"></span>
Значит ты можешь написать в "Вопросы авторам" вопрос о том, зачем они учат на лайве нарушать критерии которые сами же и написали :)

2021-11-07 15:02 UTC, Dima-Dim commented on catalog.html
> +                  <span class="filter-button-apply">Применить</span>
Почему не менять этот цвет через саму кнопку?

2021-11-07 15:14 UTC, merged